Ignore unnecessary_box_returns pedantic clippy lint
    error: boxed return of the sized type `de::Error`
        --> src/de.rs:1445:22
         |
    1445 |     fn eof(&self) -> Box<Error> {
         |                      ^^^^^^^^^^ help: try: `de::Error`
         |
         = help: changing this also requires a change to the return expressions in this function
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_box_returns
         = note: `-D clippy::unnecessary-box-returns` implied by `-D clippy::pedantic`

    error: boxed return of the sized type `de::Error`
        --> src/de.rs:1449:49
         |
    1449 |     fn token_error(&self, error: TokenError) -> Box<Error> {
         |                                                 ^^^^^^^^^^ help: try: `de::Error`
         |
         = help: changing this also requires a change to the return expressions in this function
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_box_returns

    error: boxed return of the sized type `de::Error`
        --> src/de.rs:1472:52
         |
    1472 |     fn error(&self, at: usize, kind: ErrorKind) -> Box<Error> {
         |                                                    ^^^^^^^^^^ help: try: `de::Error`
         |
         = help: changing this also requires a change to the return expressions in this function
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_box_returns

    error: boxed return of the sized type `de::Error`
        --> src/de.rs:1501:57
         |
    1501 |     fn from_kind(at: Option<usize>, kind: ErrorKind) -> Box<Self> {
         |                                                         ^^^^^^^^^ help: try: `de::Error`
         |
         = help: changing this also requires a change to the return expressions in this function
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_box_returns

    error: boxed return of the sized type `de::Error`
        --> src/de.rs:1512:48
         |
    1512 |     fn custom(at: Option<usize>, s: String) -> Box<Self> {
         |                                                ^^^^^^^^^ help: try: `de::Error`
         |
         = help: changing this also requires a change to the return expressions in this function
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_box_returns